### ISSUE TITLE
a little bug 

### ISSUE THREAD

**Issue by jiaqiwang969** [davidem88/rhoEnergyFoam#1]
https://github.com/davidem88/rhoEnergyFoam/blob/186c6bbacc6fdbaf5e70bd301dbb857a5bc60efc/rhoEnergyFoam_v6/src/sensor.H#L8

Hi, maybe there is a little bug:
change eplison to eps?

**Comment by davidem88** [comment]
No, why do you say so? It seems correct to me. epsilon is read from input and it's a scalar

**Comment by jiaqiwang969** [comment]
That because when I am debugging, I found the bug:
```
—> FOAM FATAL ERROR: 
LHS and RHS of + have different dimensions
     dimensions : [0 0 -2 0 0 0 0] + [0 0 0 0 0 0 0]
```

divU2[icell] + rotU2[icell] + epsilon？

epsilon is dimensions [0 0 0 0 0 0 0]， and it sends the value to eps, with its dimension [0 0 -2 0 0 0 0].

I am not sure why in cpu, it not show bug, In GPU version debugging, I found it.

**Comment by davidem88** [comment]
As far as I know, in the CPU version of OF physical dimensions are not checked in the loops. That is why it is working anyway.
