### ISSUE TITLE
Turbulent channel flow case

### ISSUE THREAD

**Issue by OYYO1999** [davidem88/rhoEnergyFoam#3]
Hi 

I have recently been focusing on solving turbulent channel flow for compressible flows using OpenFOAM.

I read your article about the rhoenergyFoam solver and was very interested, which contains results of turbulent channel flow. Can you provide me with case or tutorial of turbulent channel flow for reference?

Thanks

**Comment by davidem88** [comment]
I updated the code for OF_v6 including the possibility of doing channel flow with fixed bulk Mach number and fixed bulk temperature. I also added a tutorial case for laminar channel flow. For turbulent channel flow you can use the same setup, changing the mesh and the Reynolds number. For channel flow the variable channelCase should be set to 'true' in the input file. If you set Tbulk<0 then the bulk velocity if free to evolve, as in this paper https://doi.org/10.1016/j.ijheatfluidflow.2016.01.007. 

For smooth channel flow simulations, I suggest using STREAmS-2(https://github.com/STREAmS-CFD/STREAmS-2), as it is much faster than OpenFOAM.

For subsonic/incompressible flow cases, you can compare the mean flow results to the ones of ThermoTurb (www.thermoturb.com), which can also be used to set the correct bulk Reynolds number of the simulation.

**Comment by OYYO1999** [comment]
Wow, thank you very much for taking the time to update the code and answer my question. I will study carefully.

**Comment by OYYO1999** [comment]
![2024-11-08 190208](https://github.com/user-attachments/assets/8f898832-170a-4ca7-bdcb-77b5eb867efa)
Hi, I read the code carefully and now have a small question: why is trelax=1 used here? This will not change the value of Tbulk_target later. Is trelax used as a relaxation factor to adjust the speed of convergence to Tbulk?

**Comment by davidem88** [comment]
trelax is set to 1, meaning that Tbulk is set to the input value from the begin of the simulation. Optionally, you can make trelax a function of time, to make it converge to a given value progressively.

**Comment by OYYO1999** [comment]
OK, I understand, Thanks for your answer.

**Comment by OYYO1999** [comment]
// Note: these are the properties for a "normalised" inviscid gas
//       for which the speed of sound is 1 m/s at a temperature of 1K
//       and gamma = 7/5
I have another question. I found that the thermophysicalProperties used in the solver are different from the conventional ones. Will the initial values ​​of velocity, pressure and temperature be different from the conventional ones? How should I consider this conversion relationship? It seems to be a dimensionless relationship.

**Comment by davidem88** [comment]
The normalization is the same as in STREAmS and it is explained here https://streams-cfd.github.io/STREAmS-2/manual/flow_cases.html. Also partially explained in the file attached
[Nondimensional variables.pdf](https://github.com/user-attachments/files/17681558/Nondimensional.variables.pdf)

**Comment by OYYO1999** [comment]
Thanks for your answer, I understand most of the conversions. But I don't quite understand the conversion of Sutherland. _Ts=0.40417_ may be _Ts*/Tref=110.4/273.15_, but I am a little confused about the conversion of _As_, why is it 0.01？

**Comment by davidem88** [comment]
Yes, T_s=110.4/273.15. A_s depends on the viscosity as explained on slide 3. In the tutorial, it is just set to a low value, but this does not matter in this case because in the laminar case the solution is basically Reynolds number independent.

**Comment by OYYO1999** [comment]
OK，Thanks for your answer, I understand. 
I may have found a small bug:
![2024-11-09 160858](https://github.com/user-attachments/assets/f7062b50-5f77-4e64-a7a3-c85141783fdd)
Here _drhoUx_ may be _drhoUxl_ .

**Comment by davidem88** [comment]
Thanks

**Comment by OYYO1999** [comment]
Hi, I found a problem in the tutorials, maybe I debugged it wrong, as follows:
![2024-11-09 210452](https://github.com/user-attachments/assets/6cd8f9e7-0fc9-4805-9b6d-4c30dfe89058)
_dpdx_prt.value()  drhoUx_prt.value()  Tbulk_prt.value() rhob_prt.value()_： All are zero, which seems incorrect.

**Comment by davidem88** [comment]
You have to set channelCase true in controlDict

**Comment by OYYO1999** [comment]
Oh, yes, I forgot, thanks.
When I tested in parallel, I found a code missing.
![2024-11-10 101525](https://github.com/user-attachments/assets/34541a19-7e3e-435d-bc12-6f4aeacfda6b)
The _rhob_ does not have MPI _reduce_.

**Comment by davidem88** [comment]
It does not matter because it is not used after this. It is already defined in pressureGrad.H

**Comment by OYYO1999** [comment]
Yes, but parallel diagnosis of _Tbulk_ seems to be wrong, because it is divided by an incorrect _rhob_.

**Comment by davidem88** [comment]
Yes, you're right. It has been fixed

**Comment by OYYO1999** [comment]
Hi, I would like to ask a simple question about _tbforce.H_ handling of average temperature. Its main idea is to compensate the loss of average temperature with _rhoE_ after solution; but after this compensation, a compensation value is added to each grid, and then the solution is completed. This seems to cause some oscillation of grid values ?such as the grid near the wall.

**Comment by davidem88** [comment]
I didn't not fully understand what you mean. tbforce.H effectively adds a uniform heat source/sink to the energy equation. This cannot induce oscillations

**Comment by OYYO1999** [comment]
Sorry, I haven't replied for a long time.
Maybe I didn't express it clearly, or maybe I misunderstood. The idea of ​​the solver I understand is: by adding a uniform heat source/sink after the RK step, it seems that at the boundary, there is no energy equation constraint, and it may not be conserved, as shown in the following simple figure:
![2024-11-12 142856](https://github.com/user-attachments/assets/14780747-763d-4bfa-9b6c-bb7e97b1b631)

**Comment by davidem88** [comment]
I still don't understand, sorry. The procedure for imposing Tbulk is basically the same used for enforcing a constant bulk velocity.

**Comment by OYYO1999** [comment]
OK, Thanks for your answer, I'll learn more about it.
