### ISSUE TITLE
Turbulence did not occur

### ISSUE THREAD

**Issue by OYYO1999** [davidem88/rhoEnergyFoam#4]
Hi, I try to set the channel case at turbulence.

But I met problem:
Case set: the bulk mach number, _rm=0.2_, the _Tbulk_target=1_, The _As_ in the file thermophysicalProperties was set at 1.4042;
Mesh detail as follow:
![Screenshot from 2024-11-16 17-10-25](https://github.com/user-attachments/assets/c536cc3b-00dd-43be-be0e-97db973f184a)
When t=10s, the velocity contour as follow:
![Screenshot from 2024-11-16 17-39-19](https://github.com/user-attachments/assets/dad186e0-ca8c-4986-8ded-3c2f74ad9d39)
I don't know what went wrong.

**Comment by davidem88** [comment]
The solution seems correct. The flow is laminar at this Reynolds number.
What went wrong?

**Comment by OYYO1999** [comment]
Ah, why is the bulk Mach number Ma=0.2 laminar flow here?
In fact, I may not understand how the Reynolds number is calculated in detail?

**Comment by davidem88** [comment]
Mach number has nothing to do with the flow being laminar or turbulent. The Reynolds number is determined by the viscosity. The minimum Reynolds number for having a turbulent flow is around Re=rhob*ub*h/mu=3000. Thus mu=rhob*ub*h/Re = 1*sqrt(1.4)*0.2*1/3000= 7.88810637746616e-05 ==> As = mu*(1+0.404173531026908)=0.000110762701851625
I believe GitHub is not the right place for these type of issue. Please open issues that are strictly related to the code and not to fluid mechanics.

**Comment by OYYO1999** [comment]
OK, sorry, I'll pay attention.
Thanks for your answer.
